import os
from typing import Any
import httpx


class AIService:
    def __init__(self) -> None:
        self.api_key = os.getenv("GEMINI_API_KEY", "")
        self.model = os.getenv("GEMINI_MODEL", "gemini-1.5-flash")

    async def _generate_with_gemini(self, prompt: str) -> dict[str, Any]:
        if not self.api_key:
            return {
                "content": "No GEMINI_API_KEY configured. Returning safe local template response.",
                "confidence": 0.35,
                "reasoning": "Environment key missing.",
            }

        url = f"https://generativelanguage.googleapis.com/v1beta/models/{self.model}:generateContent?key={self.api_key}"
        payload = {"contents": [{"parts": [{"text": prompt}]}]}

        for _ in range(2):
            try:
                async with httpx.AsyncClient(timeout=20.0) as client:
                    response = await client.post(url, json=payload)
                    response.raise_for_status()
                    data = response.json()
                    text = data.get("candidates", [{}])[0].get("content", {}).get("parts", [{}])[0].get("text", "")
                    return {
                        "content": text or "Generated response unavailable.",
                        "confidence": 0.78,
                        "reasoning": "Generated by Gemini model with structured prompt.",
                    }
            except httpx.HTTPError:
                continue

        return {
            "content": "Temporary AI service fallback response.",
            "confidence": 0.4,
            "reasoning": "Upstream request failed; fallback returned.",
        }

    async def generate_email(self, event_name: str, audience: str, sponsor_name: str, tone: str) -> dict[str, Any]:
        prompt = (
            "Return JSON with keys subject,greeting,intro,value_proposition,audience_relevance,cta,signature. "
            f"Event: {event_name}. Audience: {audience}. Sponsor: {sponsor_name}. Tone: {tone}."
        )
        return await self._generate_with_gemini(prompt)

    async def generate_proposal(self, event_name: str, audience: str, sponsor_name: str) -> dict[str, Any]:
        prompt = (
            "Return JSON with event_overview,sponsor_benefits,marketing_opportunities,audience_analysis,packages. "
            f"Event: {event_name}. Audience: {audience}. Sponsor: {sponsor_name}."
        )
        return await self._generate_with_gemini(prompt)
